spring:
  datasource:
    source:
      jdbc-url: jdbc:oracle:thin:@192.168.0.100:1521:xe
      username: ASPUSER
      password: ASPUSER
      driver-class-name: oracle.jdbc.OracleDriver
      connection-timeout: 3000
      validation-timeout: 3000
      minimum-idle: 5
      max-lifetime: 240000
      maximum-pool-size: 20
    target:
      jdbc-url: jdbc:mysql://192.168.0.100:33062/hullaro?rewriteBatchedStatements=true
      username: hullaro
      password: hullaro
      driver-class-name: org.mariadb.jdbc.Driver
      hikari:
        connection-timeout: 3000
        validation-timeout: 3000
        minimum-idle: 5
        max-lifetime: 240000
        maximum-pool-size: 20
#  main:
#    allow-bean-definition-overriding: true
logging:
  level:
    ROOT: WARN
    com.eveningbread.demo: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.transaction: TRACE
devtools:
  livereload:
    enabled: true
  restart:
    enabled: false

server:
  servlet:
    register-default-servlet: true

pebble:
  cache : false
  suffix : .html

